<?php

declare(strict_types=1);

namespace Tests\Unit\Governance\Analyze\Support;

use Closure;
use App\Support\Governance\Analyze\AnalysisContext;
use App\Support\Governance\Analyze\Contracts\Detector;
use App\Support\Governance\Analyze\Enums\Confidence;
use App\Support\Governance\Analyze\Enums\FindingType;
use App\Support\Governance\Analyze\Enums\RiskLevel;
use App\Support\Governance\Analyze\Evidence;
use App\Support\Governance\Analyze\Finding;

final class AnalyzeTestFactory
{
    public static function finding(
        string $id = 'F1',
        RiskLevel $risk = RiskLevel::HIGH,
        FindingType $tur = FindingType::RUNTIME_RISK,
        string $title = 'Test finding',
        string $summary = 'Test summary',
    ): Finding {
        return new Finding(
            id: $id,
            title: $title,
            tur: $tur,
            risk: $risk,
            confidence: Confidence::HIGH,
            layer: 'governance',
            summary: $summary,
            evidence: [new Evidence(file: 'tests/fixture.php', line: 12, snippet: 'fixture')],
            safeAction: 'Review and remediate',
            detector: 'TestDetector',
            impact: ['runtime ambiguity'],
            tags: ['test'],
        );
    }

    public static function detector(
        string $slug,
        RiskLevel $risk,
        ?callable $onDetect = null,
    ): Detector {
        $closure = $onDetect !== null ? Closure::fromCallable($onDetect) : null;

        return new class ($slug, $risk, $closure) implements Detector {
            public function __construct(
                private readonly string $slugValue,
                private readonly RiskLevel $riskValue,
                private readonly ?Closure $onDetect,
            ) {
            }

            public function slug(): string
            {
                return $this->slugValue;
            }

            public function title(): string
            {
                return ucfirst($this->slugValue);
            }

            public function detect(AnalysisContext $context): array
            {
                if ($this->onDetect !== null) {
                    return ($this->onDetect)($context);
                }

                return [
                    AnalyzeTestFactory::finding(
                        id: strtoupper($this->slugValue) . '_F1',
                        risk: $this->riskValue,
                        title: 'Detector ' . $this->slugValue,
                        summary: 'Generated by test detector',
                    ),
                ];
            }
        };
    }
}
