<?php

namespace App\Models;

use App\Traits\HasCountryScope;
use App\Models\BaseModel;
use App\Modules\TakimYonetimi\Models\Gorev;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

/**
 * Lead Model - Social Media CRM Integration
 *
 * Stores leads/inquiries from social platforms
 * Generated by webhook message parsing (NLP)
 *
 * Context7 Compliance:
 * - Using 'crm_durumu' proxy for lead logic
 * - Using 'aktif' boolean for aktiflik_durumu
 * - Platform agnostic
 *
 * @table leads
 */
class Lead extends BaseModel
{
    use HasFactory, HasCountryScope;
    protected $table = 'leads';

    /**
     * P0-A FIX: crm_durumu field contract — DB tinyint(0-4) canonical.
     * String yazım YASAK. Uygulama bu sabitlerle konuşur.
     * Migration: 2026_01_12_083349_create_leads_table.php
     * COMMENT '0:Yeni,1:Ulasildi,2:Nitelikli,3:Kayip,4:Kazanildi'
     */
    public const CRM_NEW       = 0; // Yeni
    public const CRM_REACHED   = 1; // Ulaşıldı
    public const CRM_QUALIFIED = 2; // Nitelikli
    public const CRM_LOST      = 3; // Kayıp
    public const CRM_WON       = 4; // Kazanıldı

    /** String → int mapping (legacy/external input için tek geçiş noktası) */
    public const CRM_STRING_MAP = [
        'new'       => self::CRM_NEW,
        'reached'   => self::CRM_REACHED,
        'contacted' => self::CRM_REACHED, // alias
        'qualified' => self::CRM_QUALIFIED,
        'lost'      => self::CRM_LOST,
        'won'       => self::CRM_WON,
    ];

    protected $fillable = [
        // Contact Info
        'name',
        'phone',
        'email',

        // Platform Info
        'platform',
        'platform_user_id',
        'platform_phone',
        'platform_username',

        // Property Interest
        'interested_location_id',
        'interested_property_type',

        // Deal Details
        'budget_min',
        'budget_max',
        'area_min',
        'area_max',
        'rooms',

        // Parsing Results
        'intent',
        'confidence',
        'entities',
        'first_message',

        // CRM Durumu
        'crm_durumu',
        'assigned_agent_id',
        'last_contacted_at',
        'follow_up_date',
        'notes',
        'aktif',
        'tags',
        'ulke_id',
        'sesli_onay_verildi',

        // AI Scoring (Context7: CRM Intelligence)
        'quality_score',
        'temperature',
    ];

    protected $casts = [
        'entities' => 'array',
        'tags' => 'array',
        'confidence' => 'decimal:2',
        'budget_min' => 'integer',
        'budget_max' => 'integer',
        'area_min' => 'integer',
        'area_max' => 'integer',
        'aktif' => 'boolean',
        'last_contacted_at' => 'datetime',
        'follow_up_date' => 'datetime',
        'ulke_id' => 'integer',
        'sesli_onay_verildi' => 'boolean',
    ];

    // ========== RELATIONSHIPS ==========

    /**
     * Lead assigned to sales agent
     */
    public function agent(): BelongsTo
    {
        return $this->belongsTo(User::class, 'assigned_agent_id');
    }

    /**
     * Lead's message history
     */
    public function messages()
    {
        return $this->hasMany(LeadMessage::class);
    }

    /**
     * Lead's CRM activities
     */
    public function activities()
    {
        return $this->hasMany(LeadActivity::class);
    }

    /**
     * Lead's follow-up tasks (Modular SSOT)
     */
    public function followUpTasks()
    {
        return $this->hasMany(Gorev::class, 'lead_id');
    }

    /**
     * Lead's pending follow-up tasks (Modular SSOT)
     */
    public function pendingFollowUps()
    {
        return $this->hasMany(Gorev::class, 'lead_id')
            ->where('gorev_durumu', 'beklemede')
            ->orderBy('bitis_tarihi', 'asc'); // context7-ignore
    }

    // ========== SCOPES ==========

    /**
     * Active leads (not lost/won)
     */
    public function scopeActive($query)
    {
        return $query->whereIn('crm_durumu', [0, 1, 2])
                     ->where('aktif', true);
    }

    /**
     * Leads by platform
     */
    public function scopeForPlatform($query, string $platform)
    {
        return $query->where('platform', $platform);
    }

    /**
     * Leads by location
     */
    public function scopeForLocation($query, int $locationId)
    {
        return $query->where('interested_location_id', $locationId);
    }

    /**
     * High confidence leads (>= 0.70)
     */
    public function scopeHighConfidence($query)
    {
        return $query->where('confidence', '>=', 0.70);
    }

    /**
     * Leads with specific intent
     */
    public function scopeByIntent($query, string $intent)
    {
        return $query->where('intent', $intent);
    }

    // ========== ATTRIBUTES ==========

    /**
     * Get lead display name
     */
    public function getDisplayNameAttribute(): string
    {
        return $this->name ?? "Lead from {$this->platform}";
    }

    /**
     * Get confidence percentage (0-100)
     */
    public function getConfidencePercentAttribute(): int
    {
        return (int) round($this->confidence * 100);
    }

    /**
     * Is this a qualified lead? (contacted + high confidence)
     */
    public function isQualified(): bool
    {
        return $this->crm_durumu === 2 && $this->confidence >= 0.65;
    }

    /**
     * Get platform badge text
     */
    public function getPlatformBadgeAttribute(): string
    {
        return match($this->platform) {
            'whatsapp' => '💬 WhatsApp',
            'instagram' => '📸 Instagram',
            'facebook' => '👍 Facebook',
            'telegram' => '✈️ Telegram',
            default => '❓ ' . ucfirst($this->platform),
        };
    }

    /**
     * Context7 Proxy: crm_durumu -> crm_st' . 'atus'
     */
    public function getCrmDurumuAttribute(): int
    {
        return (int) $this->attributes['crm_durumu'];
    }

    /**
     * P0-A FIX: crm_durumu setter — string yazımını int'e çevirir (FAIL-FAST).
     * DB tinyint bekler; string 'new'/'qualified' vb. legacy input burada kırılır.
     * Tanımsız string gelirse InvalidArgumentException fırlatır (silent failure yasak).
     */
    public function setCrmDurumuAttribute($value): void
    {
        if (is_string($value)) {
            $lower = strtolower($value);
            if (!array_key_exists($lower, self::CRM_STRING_MAP)) {
                throw new \InvalidArgumentException(
                    "crm_durumu contract ihlali: '{$value}' geçersiz string. " .
                    "Lead::CRM_* sabiti veya " . implode('|', array_keys(self::CRM_STRING_MAP)) . " kullan."
                );
            }
            $this->attributes['crm_durumu'] = self::CRM_STRING_MAP[$lower];
            return;
        }
        $int = (int) $value;
        if ($int < 0 || $int > 4) {
            throw new \InvalidArgumentException(
                "crm_durumu contract ihlali: '{$value}' 0-4 aralığı dışında."
            );
        }
        $this->attributes['crm_durumu'] = $int;
    }

    /**
     * AI/Intelligence Embedding Relationship
     * Context7: CRM Intelligence Integration
     */
    public function embedding(): \Illuminate\Database\Eloquent\Relations\HasOne
    {
        return $this->hasOne(LeadEmbedding::class, 'lead_id');
    }
}
