<?php

namespace App\Services\Governance\Context;

use Illuminate\Support\Facades\File;

class ProjectionBuilderService
{
    /**
     * @var EventLoggerService
     */
    protected $eventLogger;

    public function __construct(EventLoggerService $eventLogger)
    {
        $this->eventLogger = $eventLogger;
    }

    /**
     * Build all projections based on current event logs
     */
    public function buildProjections(): array
    {
        $events = $this->eventLogger->getEvents();
        
        if (empty($events)) {
            return [
                'success' => false,
                'message' => 'No events found to build projections.',
            ];
        }

        $this->ensureDirectoriesExist();

        $this->buildLatestStatus($events);
        $this->buildCurrentState($events);
        $this->buildGovernanceDelta($events);

        return [
            'success' => true,
            'message' => 'Projections built successfully.',
            'event_count' => count($events),
        ];
    }

    /**
     * Generate .ai/memory/latest-status.md
     */
    protected function buildLatestStatus(array $events): void
    {
        $latestEvents = array_slice(array_reverse($events), 0, 10);
        $content = "# Yalıhan 2026 - Latest Operational Status\n\n";
        $content .= "> Generated automatically by SAB Context Builder at " . now()->toIso8601String() . "\n\n";

        foreach ($latestEvents as $event) {
            $date = \Carbon\Carbon::parse($event['timestamp'])->timezone('Europe/Istanbul')->format('Y-m-d H:i');
            $eventStatus = strtoupper($event['event_status'] ?? 'UNKNOWN');
            $scope = $event['scope'] ?? 'General';
            $summary = $event['summary'] ?? 'No summary provided.';
            $source = $event['source'] ?? 'manual';
            
            $content .= "### [{$eventStatus}] {$scope}\n";
            $content .= "- **Time:** {$date}\n";
            $content .= "- **Source:** {$source}\n";
            $content .= "- **Summary:** {$summary}\n\n";
        }

        File::put(base_path('.ai/memory/latest-status.md'), $content);
    }

    /**
     * Generate .ai/context/current-state.generated.md
     */
    protected function buildCurrentState(array $events): void
    {
        $latestEvent = end($events);
        
        $content = "# System Current State (Generated)\n\n";
        $content .= "> Note: This file is auto-generated by SAB Projection Builder. Do not edit manually.\n\n";
        $content .= "## Last Recorded Event\n";
        $content .= "- **Category:** " . ($latestEvent['event_type'] ?? 'N/A') . "\n";
        $content .= "- **Scope:** " . ($latestEvent['scope'] ?? 'N/A') . "\n";
        $content .= "- **Result:** " . ($latestEvent['event_status'] ?? 'N/A') . "\n";
        $content .= "- **Time:** " . ($latestEvent['timestamp'] ?? 'N/A') . "\n";
        
        if (isset($latestEvent['release_state'])) {
            $content .= "- **Release State:** " . $latestEvent['release_state'] . "\n";
        }

        $content .= "\n## Pipeline State\n";
        $content .= "The projection pipeline is active and logging events. The current context reflects operations up to the last event timestamp.\n";

        File::put(base_path('.ai/context/current-state.generated.md'), $content);
    }

    /**
     * Generate .ai/context/governance-delta.generated.md
     */
    protected function buildGovernanceDelta(array $events): void
    {
        // Filter events related to governance/quality gates
        $govEvents = array_filter($events, function($e) {
            $eventType = $e['event_type'] ?? '';
            return in_array($eventType, ['remediation_completed', 'quality_gate_result', 'preflight_result']);
        });

        $content = "# Governance & Technical Debt Delta (Generated)\n\n";
        $content .= "> Tracks the impact of recent changes on the SAB Baseline and Governance standards.\n\n";

        if (empty($govEvents)) {
            $content .= "No governance events recorded yet.\n";
        } else {
            $content .= "### Recent Governance Updates\n\n";
            foreach (array_slice(array_reverse($govEvents), 0, 5) as $event) {
                $date = \Carbon\Carbon::parse($event['timestamp'])->timezone('Europe/Istanbul')->format('Y-m-d H:i');
                $eventStatus = $event['event_status'] ?? 'N/A';
                $content .= "- **[{$date}]** {$event['scope']}: {$event['summary']} (Result: {$eventStatus})\n";
            }
        }

        File::put(base_path('.ai/context/governance-delta.generated.md'), $content);
    }

    /**
     * Make sure required directories exist
     */
    protected function ensureDirectoriesExist(): void
    {
        $dirs = [
            base_path('.ai/memory'),
            base_path('.ai/context'),
        ];

        foreach ($dirs as $dir) {
            if (!File::isDirectory($dir)) {
                File::makeDirectory($dir, 0755, true);
            }
        }
    }
}
