<?php

/**
 * 🛡️ SAB DATABASE GUARD CONFIGURATION
 *
 * @generated_from .sab/authority.json
 *
 * 🛑 DO NOT EDIT THIS FILE MANUALLY.
 * 💡 Run 'npm run authority:compile' to regenerate.
 */

return [
    'generated_from' => '.sab/authority.json',
    'last_updated' => 'STABLE',
    'tables' => [
    ],
];
