<?php

namespace App\Services\Governance\AuthorityMap;

class AuthorityMapMarkdownFormatter
{
    /**
     * Formats the domain objects into the final Markdown string.
     *
     * @param array $projectData
     * @return string
     */
    public function format(array $projectData): string
    {
        $version = $projectData['version'];
        $domains = $projectData['domains'];
        $generatedAt = now()->toIso8601String();

        $markdown = "# Yalıhan Bekçi Authority Map (Companion Projection)\n\n";
        $markdown .= "> [!WARNING] STATUS: DRAFT COMPANION PROJECTION\n";
        $markdown .= "> *   **Source:** `.sab/authority.json`\n";
        $markdown .= "> *   **Authority:** False (This document is a human-readable projection, not the system source of truth)\n";
        $markdown .= "> *   **Human Readable Projection:** True\n";
        $markdown .= "> *   **Source Version:** {$version}\n";
        $markdown .= "> *   **Generated At:** {$generatedAt}\n";
        $markdown .= "> *   *Machine-readable authority source remains `.sab/authority.json`.*\n\n";

        $markdown .= "<!-- MANUAL EDIT FORBIDDEN: This file is auto-generated by sab:authority-map:generate -->\n\n";

        $markdown .= "Bu belge, `.sab/authority.json` içindeki makine okunabilir konfigürasyonu insan okunabilir bir haritaya dönüştürmek (projection) amacıyla üretilmiştir. Ana yönetişim kuralları, terminal komutları ve AI davranış yetkileri burada özetlenmiştir.\n\n";
        $markdown .= "---\n\n";

        $counter = 1;
        foreach ($domains as $domain) {
            $markdown .= "## {$counter}. {$domain['title']}\n\n";
            $markdown .= "*   **Domain:** {$domain['domain']}\n";
            $markdown .= "*   **Authoritative File/Path:** {$domain['path']}\n";
            $markdown .= "*   **Rol:** {$domain['role']}\n";
            $markdown .= "*   **Açıklama:** {$domain['description']}\n";
            $markdown .= "*   **Update Policy:** {$domain['update_policy']}\n";
            $markdown .= "*   **Overwrite Policy:** {$domain['overwrite_policy']}\n";
            $markdown .= "*   **Drift Note:** {$domain['drift_note']}\n\n";
            $counter++;
        }

        $markdown .= "---\n";
        $markdown .= "*Generated by Yalıhan Governance Agent. This is a Human-Readable Draft Companion.*\n";

        return $markdown;
    }
}
