<?php

namespace Database\Factories;

use App\Models\PropertyConfigVersion;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\PropertyConfigVersion>
 */
class PropertyConfigVersionFactory extends Factory
{
    protected $model = PropertyConfigVersion::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        return [
            'version_hash' => $this->faker->sha256(),
            'description' => $this->faker->sentence(),
            'yonetim_durumu' => 'DRAFT', // Default state
            'snapshot_json' => [
                'rules' => [],
                'templates' => [],
                'assignments' => []
            ],
            'signature' => null, // Signature generated by service
            'created_by' => 1, // Assuming admin user exists or overridden
        ];
    }

    /**
     * Indicate that the version is active.
     */
    public function active(): static
    {
        return $this->state(fn (array $attributes) => [
            'yonetim_durumu' => 'AKTIF',
        ]);
    }
}
